### ISSUE TITLE
Rules Confirmation

### ISSUE THREAD

**Issue by kaitogoto7** [mberk/rss-euro-2020-prediction-competition#1]
Hello thanks for hosting this competition, sounds very interesting, I would like to clarify rule #2 :
"Entrants are free to use any data they wish, provided it is publicly available".
Does data scraped from websites count as "publicly available"?

I also assume there is a "one submission per person" rule...

**Comment by mberk** [comment]
Yes, scraped data is fine but the scraping code should be supplied with the rest of the code used to build the submission so the results can be reproduced by the judging panel.

Participants can make multiple submissions as a means to update predictions but only the most recent submission will be considered their entry and scored.

**Comment by kaitogoto7** [comment]
Thanks for your reply. What I meant by the "one submission per person" rule is that people can't game the system by making several email accounts to make several submissions that count. A good way to detect if someone is doing this is to entitle them to supply a phone number and/or home address in advance to send them their prize if they win (unless someone tries to buy several houses to get an advantage in this competition LOL).

**Comment by mberk** [comment]
We will certainly be doing our best to prevent participants from cheating :smile:
