### ISSUE TITLE
Rule #8

### ISSUE THREAD

**Issue by kaitogoto7** [mberk/rss-euro-2020-prediction-competition#2]
Hello, when it says "two entries with the best log-score (see Scoring below) will win a prize (see Prizes below) along with a third entry chosen by the judging panel based on the methodology used".

Are we allowed to include a written report in our submission file to improve our chances of getting the prize for "third entry chosen by the judging panel based on the methodology used"?

**Comment by mberk** [comment]
Any documentation, such as the report you mention, that can help the judging panel understand your code/approach will be appreciated!
