### ISSUE TITLE
Probabilities Sum =/= 1

### ISSUE THREAD

**Issue by kaitogoto7** [mberk/rss-euro-2020-prediction-competition#3]
Hello, I was wondering, what happens to my score if my submission's probability prediction does not add to 1? For example, if I predict Team 1 to beat Team 2 at 90% probability and the opposite at 20% probability (even though it should be 10%).

**Comment by mberk** [comment]
We will normalise your predictions so that they sum to 1. For example, in this case 0.9 / 1.1 and 0.2 / 1.1
