### ISSUE TITLE
Live Leaderboard

### ISSUE THREAD

**Issue by OliverHatfield** [mberk/rss-euro-2020-prediction-competition#4]
Hi there, I was wondering if you still had ambitions to get the live leaderboard up and running? It would be really interesting to see how we were doing compared to the other teams, even if the updates were only infrequent.

**Comment by mberk** [comment]
Yes, I'm working on it! Will hopefully be available later today

**Comment by OliverHatfield** [comment]
Super! No problem at all, just wanted to check. Thanks, and good luck with getting it up and running!

**Comment by mberk** [comment]
Leaderboard available here: https://github.com/mberk/rss-euro-2020-prediction-competition/blob/master/leaderboard.csv

**Comment by OliverHatfield** [comment]
Neat! Going better than I'd hoped... Thanks for this and the rest of your work on the competition!
