### ISSUE TITLE
Cost function during knockout games

### ISSUE THREAD

**Issue by bibblybobbly** [mberk/rss-euro-2020-prediction-competition#5]
Hi,

I have emailed a similar comment several days ago so apologies if this is duplication but I wanted to ensure my question was seen before the knockouts resumed. Thanks for running the tournament, I'm enjoying keeping track of the table and my anonymous competitors!

On the group stages, probabilities are normalised by L43-45 of`'score_submissions.py` to ensure all possible outcomes sum to a probability of 1.

For the knockout rounds, this is not done again. It seems that the competition has defined draws as impossible events in knockout round matches, suggesting P(team1)+P(team2) =1. In practice, a non-zero likelihood is  given to the impossible draw . Therefore, should knockout round team1 and team2 probabilities similarly be normalised akin to how group matches are, but ignoring the probability for draws please?

i.e

`df_ko["p_team1_win"] = df_ko["p_team1_win"]/df_ko[["p_team1_win", "p_team2_win"]].sum(axis=1)`

Thanks for any clarification you can give here!

Again in the interests of disclosure I am asking this because I have non zero probabilities for draws in knockout round games, a subtlety to the rules that I did not appreciate when submitting my entry.

Best wishes

**Comment by mberk** [comment]
Thanks for pointing this out

I have set the probabilities for draws for KO matches to 0 prior to normalisation

Please check the updated code in case you have any additional comments before I close this issue

**Comment by bibblybobbly** [comment]
Hi, 

Ah fantastic, thank you for your help! Apologies for the slow response, all looks great to me, I have no further issues
